source "https://rubygems.org"

gem "middleman", ">=3.0.13"
gem "middleman-favicon-maker"
gem "middleman-livereload"
gem "addressable"
gem "haml"
gem "susy", ">=1.0.8"
#gem "redcarpet"
gem "yui-compressor"
